### ISSUE TITLE
[Bug Report] Docker build fails

### ISSUE THREAD

**Issue by DanyTPG** [juicity/juicity#114]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

Hi.
Currently building the docker image with the current Dockerfile results in build failure.
changing the build image from `golang:1.20-alpine` to `golang:1.21-alpine` will fix this issue.

**Comment by yqlbu** [comment]
@DanyTPG Thanks for raising this. Would you mind raising a PR for the fix you proposed?

**Comment by DanyTPG** [comment]
Sure #115
