### ISSUE TITLE
[Support Request]  x86-x64 armv7a

### ISSUE THREAD

**Issue by MataAzi** [juicity/juicity#118]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

Hello I'm trying to create android client for juicity but only armv8 are in release page so can you add other arch's or help with building them?

**Comment by yqlbu** [comment]
You may find artifacts in the [latest release](https://github.com/juicity/juicity/releases/tag/v0.3.0)

<img width="720" alt="image" src="https://github.com/juicity/juicity/assets/31861128/2a7ed40a-efea-4bd2-ab91-fc98db3823ef">

**Comment by MataAzi** [comment]
> You may find artifacts in the [latest release](https://github.com/juicity/juicity/releases/tag/v0.3.0)
> 
> <img alt="image" width="720" src="https://user-images.githubusercontent.com/31861128/266833643-2a7ed40a-efea-4bd2-ab91-fc98db3823ef.png">

Thanks :)
