### ISSUE TITLE
[Enhancement] Add Juicity to sing-box core

### ISSUE THREAD

**Issue by ellahmezar** [juicity/juicity#148]
### Improvement Suggestion

Hi ,
Hope you're doing well .
You can talk ,and cooperate with @SagerNet for adding Juicity in sing-box core both in inbound and outbound mode

### Potential Benefits

People can tuunel from other plugins to Juicity ,or from Juicity to other plugins
The other advantage is that people can conncet from Nekobox to Juicity **directly** (Without any plugins just like other connection ways such as TUIC , Hysteria ,and . . . )
It reduces ping both in Juicity conncetion itself ,and the ping shown in Nekobox app .
Hope doing this faster .
Best Regards 🌹🌱

**Comment by MarksonHon** [comment]
@ellahmezar Thank you for your support, but none of our developers are members of SagerNet. It would be better for you to submit your requirements to SagerNet.
