### ISSUE TITLE
[Feature Request] : Update Juicity plugin for NekoBox to 0.4.0

### ISSUE THREAD

**Issue by ellahmezar** [juicity/juicity#151]
### Greetings

Hi dear Juicity team !
Hope you're doing great 🌱🌹

### Feature Request

Please update Juicity plugin for Nekobox to the latest version of Juicity (0.4.0) .
Many thanks 🌹

**Comment by mzz2017** [comment]
@ellahmezar Raise the issue at https://github.com/MatsuriDayo/plugins instead.
