### ISSUE TITLE
[Bug Report] Fix Juicity plugin parameters in NekoBox

### ISSUE THREAD

**Issue by ellahmezar** [juicity/juicity#152]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

Hi dear Juicity team !
Thanks for your efforts 🙏🏻🌹
This is Juicity plugin environment in NekoBox .
It can be better by these editions : 

### Steps to Reproduce

1. Change uuid to "UUID" ,and default parameter should be "Not set "
2.  Change password to "Password" .
3.  There is no SNI in server config file . It should delete totally .
4.  Change allowInsecure to "Allow Insecure"
5.  Change congestionControl to " Congestion Control " ,and add three choices ( BBR , Cubic  , New-Reno )
Till now , the latest version of plugin released for Juicity in NekoBox is 0.3.0 . Please do these changes ,and compatible the changes with Juicity ver. 0.4.0 ,and release the 0.4.0 plugin with changes that I told you above .
Sincerely Yours 🌹🙏🏻

### Environment

Juicity plugin ver 0.3.0 in Nekobox
![Screenshot_20240208_205511_NekoBox](https://github.com/juicity/juicity/assets/129280842/036adb6d-b62e-4b7f-bbbe-71fc787ee56b)

**Comment by mzz2017** [comment]
@ellahmezar Raise the issue at https://github.com/MatsuriDayo/plugins instead.
