### ISSUE TITLE
服务端用 systemctl restart juicity 后，客户端也要 重启 juicity 才能连接

### ISSUE THREAD

**Issue by chika0801** [juicity/juicity#22]
假设服务端先运行 juicity ，客户端也启动连接上服务端，客户端正常访问网页。

此时，服务端用 systemctl restart juicity 重启，客户端没有自动重连功能，需要手动关闭，再开一次程序，方能连上正常访问网页。

**Comment by mzz2017** [comment]
据观察，客户端需要等待 1 分钟左右才能反映过来

**Comment by mzz2017** [comment]
顺便一提，你使用的客户端是什么？上述观察是基于 dae 的。

**Comment by yqlbu** [comment]
> 假设服务端先运行 juicity ，客户端也启动连接上服务端，客户端正常访问网页。
> 
> 此时，服务端用 systemctl restart juicity 重启，客户端没有自动重连功能，需要手动关闭，再开一次程序，方能连上正常访问网页。

YES, this is a known issue.

**Comment by chika0801** [comment]
> 据观察，客户端需要等待 1 分钟左右才能反映过来

windows11 cmd窗口运行的 .exe。我没有等到1分钟，我试一试多等下。

**Comment by chika0801** [comment]
windows下，约28-30秒后，客户端自动重连成功。
