### ISSUE TITLE
希望增加类似 TUIC 中的 "send_window" "receive_window" 参数

### ISSUE THREAD

**Issue by chika0801** [juicity/juicity#23]
希望在客户端和服务端配置中增加这2个参数，方便自定义缓存大小，主要是为了测试极限速度，感觉能自定义这2个参数方便一些。

```
        "send_window": 33554432,
        "receive_window": 16777216
```

**Comment by mzz2017** [comment]
我对加入这个参数比较犹豫，因为我的设计理念是保持参数尽量简洁。目前 juicity 的窗口大小为 stream 32MB，connection 64MB。该窗口理论上能够使得在 500ms 的时延下单线程 512Mbps（32*8/0.5s)，双线程 1Gbps，如果时延更低，这个带宽数值将更高。

我认为这个参数是足够支撑的。欢迎你通过修改代码的方式来获得更多的测试结果，如果测试结果显示更大的窗口对于带宽有显著影响，我很乐意加入这些优化。

下面提供修改代码的方式：
1. go.mod 中取消注释 replace softwind 一行。
1. 克隆 softwind 仓库到本仓库的上一级，即与本仓库保持同级。
1. 修改 https://github.com/mzz2017/softwind/blob/b6f8b43875a9dd4efd531ee23c50eb10e1eb0f72/protocol/juicity/dialer.go#L51-L54 的值。
1. 在本仓库下使用 make CGO_ENABLED=0 重新编译。

**Comment by chika0801** [comment]
感谢你的回复。 `stream 32MB，connection 64MB` 够用了。
