### ISSUE TITLE
希望改进当服务端 log 使用 info 时，用 journalctl -u juicity --output cat -f 查看输出日志时的显示内容

### ISSUE THREAD

**Issue by chika0801** [juicity/juicity#28]
目的：想使用 info 级别时 log 输出内容为类似

`2023/07/30 11:33:22 访问者IP 请求的IP(域名) `

目前info级别不会显示访问信息，只能使用debug级别来显示

```
11:27AM DBG server.go:162 > juicity received a tcp request target=140.82.114.25:443
11:27AM DBG server.go:162 > juicity received a tcp request target=172.217.164.106:443
11:27AM DBG server.go:162 > juicity received a tcp request target=142.250.191.46:443
11:27AM DBG server.go:162 > juicity received a tcp request target=142.250.191.68:443
11:28AM DBG server.go:162 > juicity received a tcp request target=142.251.46.195:443
11:30AM DBG server.go:162 > juicity received a tcp request target=185.199.108.154:443
11:31AM DBG server.go:162 > juicity received a tcp request target=185.199.108.154:443
11:33AM DBG server.go:162 > juicity received a tcp request target=1.1.1.1:853

```

客户端使用info时能显示

```
11:27:38 [socks5] 127.0.0.1:7754 <-> 142.250.191.74:443 via
11:27:38 [socks5] 127.0.0.1:7753 <-> 142.250.191.74:443 via
11:27:39 [socks5] 127.0.0.1:7756 <-> 140.82.114.25:443 via
11:27:42 [socks5] 127.0.0.1:7758 <-> 185.199.110.133:443 via
11:27:43 [socks5] 127.0.0.1:7760 <-> 140.82.114.25:443 via
11:27:48 [socks5] 127.0.0.1:7762 <-> 172.217.164.106:443 via
11:27:49 [socks5] 127.0.0.1:7764 <-> 142.250.191.46:443 via
11:27:50 [socks5] 127.0.0.1:7766 <-> 142.250.191.68:443 via
11:28:36 [socks5] 127.0.0.1:7772 <-> 142.251.46.195:443 via
11:30:11 [socks5] 127.0.0.1:7777 <-> 185.199.108.154:443 via
11:31:33 [socks5] 127.0.0.1:7783 <-> 185.199.108.154:443 via
```

**Comment by mzz2017** [comment]
很好的建议

**Comment by KoinuDayo** [comment]
话说这个指令和journalctl -fu juicity有什么区别吗，我提到的和这个的输出似乎是一样的，还简短点

**Comment by chika0801** [comment]
> 话说这个指令和journalctl -fu juicity有什么区别吗，我提到的和这个的输出似乎是一样的，还简短点

不知道，我当时抄的sing-box里面的 ，我也学下你这条

**Comment by chika0801** [comment]
![1](https://github.com/juicity/juicity/assets/88967758/431572b3-50c6-44e7-9ac8-d6227c525dac)

![2](https://github.com/juicity/juicity/assets/88967758/35331f08-6b79-4d9c-baa5-4e05a191c395)

测试了，已经解决，感谢作者们。

**Comment by KoinuDayo** [comment]
> 
> 
> > 话说这个指令和journalctl -fu juicity有什么区别吗，我提到的和这个的输出似乎是一样的，还简短点
> 
> 不知道，我当时抄的sing-box里面的 ，我也学下你这条
> 
> ![屏幕截图 2023-07-30 213753](https://github.com/juicity/juicity/assets/88967758/12fc9a76-691a-4a76-ad13-57905b10a6fb)
> 
> 试了下，有颜色吧2333

btw， `--output` 可以换成 `-o` ，效果是一样的

**Comment by chika0801** [comment]
> > > 话说这个指令和journalctl -fu juicity有什么区别吗，我提到的和这个的输出似乎是一样的，还简短点
> > 
> > 
> > 不知道，我当时抄的sing-box里面的 ，我也学下你这条
> > ![屏幕截图 2023-07-30 213753](https://user-images.githubusercontent.com/88967758/257054478-12fc9a76-691a-4a76-ad13-57905b10a6fb.png)
> > 试了下，有颜色吧2333
> 
> btw， `--output` 可以换成 `-o` ，效果是一样的

学会了 3QU

**Comment by KoinuDayo** [comment]
> 
> 
> > 话说这个指令和journalctl -fu juicity有什么区别吗，我提到的和这个的输出似乎是一样的，还简短点
> 
> 不知道，我当时抄的sing-box里面的 ，我也学下你这条
> 
> ![屏幕截图 2023-07-30 213753](https://github.com/juicity/juicity/assets/88967758/12fc9a76-691a-4a76-ad13-57905b10a6fb)
> 
> 试了下，有颜色吧2333

问了下gpt，似乎可以将-fu默认使用cat输出https://chat.openai.com/share/f263b008-381b-4b99-988a-d8fdb106c1d7 应该可以让 `-fu` 和 `-o cat -f` 变为一样的。 ~~不过我还没试，已经躺床上了~~

**Comment by chika0801** [comment]
我新建了 `/etc/systemd/juicity.conf` 文件，重启VPS，再用 `journalctl -fu juicity` 命令查看，没有变成彩色的。等你试试

```
[juicity]
#Format=cat
```

**Comment by mzz2017** [comment]
server 的源地址还未添加，先不要关闭本 issue

**Comment by KoinuDayo** [comment]
> 我新建了 `/etc/systemd/juicity.conf` 文件，重启VPS，再用 `journalctl -fu juicity` 命令查看，没有变成彩色的。等你试试
> 

我试了下，确实是不行。但是可以用 `alias` 来方便打指令，
比如说 `alias jcat='journalctl -o cat -f -u'` ，然后使用 `jcat juicity` 就可以快捷输出cat格式的juicity日志了。
想要每次进终端都自动应用可以把指令丢到 `~/.bashrc` 或者 `~/.bash_profile` 里。

> ```
> [juicity]
> #Format=cat
> ```

~~btw，这里你其实把它注释掉了~~
~~而且是编辑 `/etc/systemd/journald.conf` ，这里的 `journald` 是固定不变的，因为我们修改的是它输出的格式~~
