### ISSUE TITLE
加入自定义CA选项/Add custom CA support

### ISSUE THREAD

**Issue by KoinuDayo** [juicity/juicity#34]
## What feature you would like us to integrate into the juicity project
自定义CA选项/Custom CA support
例如在客户端配置文件里加入/For example, add this option to the client configuration file.

```json

{
        "certificates": ["PATH/TO/CERTIFICATE_1", "PATH/TO/CERTIFICATE_2"],
}

```

## Why is this needed
在SNI白名单地区一般无法使用自己域名的证书和服务器通讯，会出现 `connection reset by peer` 的错误，加入自定义CA选项可以很好的解决这类问题，让用户可以使用自签名证书并且使用它们与服务器进行通讯。/
In SNI whitelist regions, users are often unable to communicate with servers using their own domain's certificates, leading to a `connection reset by peer` error. Adding a custom CA option can effectively resolve these issues, enabling users to utilize self-signed certificates and establish communication with servers.

**Comment by mzz2017** [comment]
很好的建议，这和 certificate pin 类似，我记得 xray 等软件支持 pin 时是给定一个 hash 值的？你知道细节吗？

**Comment by KoinuDayo** [comment]
> 顺带一提，在交互方式上，我记得 xray 等软件支持 pin 时是给定一个 hash 值的？你知道细节吗？

抱歉，我不太知道这个的细节。
我只知道pin了之后，在和服务端握手时会验证服务端证书的hash值是否和pin的对应，如果对不上那就拒绝握手
https://xtls.github.io/config/transport.html#tlsobject

**Comment by mzz2017** [comment]
@KoinuDayo 我是说，从用户的角度，该 hash 是如何计算出来的，直接使用证书是不是更加友好？你们倾向于哪种方式？

**Comment by KoinuDayo** [comment]
> 该 hash 是如何计算出来的

具体在https://xtls.github.io/config/transport.html#tlsobject 里的 `pinnedPeerCertificateChainSha256` 有仔细说，我解释不太清楚。

> 直接使用证书是不是更加友好？你们倾向于哪种方式？

我更倾向使用hash值，这样就不需要再在客户端保存一份证书。

**Comment by mzz2017** [comment]
@KoinuDayo https://github.com/juicity/juicity/pull/61 可以来测试一下吗
