### ISSUE TITLE
能否将 Releases 中生成的非 windows 用的其它平台压缩包，换成 .tar.gz 压缩格式？

### ISSUE THREAD

**Issue by chika0801** [juicity/juicity#38]
## What would you like us to support (In short summary)

我是参考了 sing-box 的 Releases 压缩格式。原因是 .zip 还需要安装 unzip 才能解压。.tar.gz 能直接使用系统内置的 tar 解压。

比如DD成 debian 11 12 或用VPS商家提供的 debian 系统没预先安装 unzip，也许真有群友尝试后失败，也不会问GPT解决方法（笑）。

**Comment by Puqns67** [comment]
同希望换成 tar 系压缩方式，直接上 tar.xz 都可以

**Comment by mzz2017** [comment]
看起来 Windows 无法简单使用 tar.gz。
我认为 zip 格式足够通用，包括 v2fly 和其他许多软件都使用它。或许依赖 unzip 并不是一个问题？

**Comment by chika0801** [comment]
感谢回复。

**Comment by mzz2017** [comment]
@yqlbu 我认为在非 windows 使用 tar.gz 是一个不错的方案，需要更多讨论？

**Comment by chika0801** [comment]
> 看起来 Windows 无法简单使用 tar.gz。

说下我遇到的，win11，winrar，下载 [sing-box-1.3.4-linux-amd64.tar.gz](https://github.com/SagerNet/sing-box/releases/download/v1.3.4/sing-box-1.3.4-linux-amd64.tar.gz) 用 winrar 打开解压后，发现文件体积比在 vps 解压出来的还大点，把文件上传到 vps 也用不了。然后我就理解为什么 sing-box 提供的 windows 的是 .zip 了。原因我没去问过GPT没研究它了。

**Comment by mzz2017** [comment]
内部讨论后，还是希望保持 zip，它可以保留文件 permissions，该 issue 先关闭了。
