### ISSUE TITLE
能否提供TLS1.3里支持的chacha20-poly1305套件和socks5鉴权

### ISSUE THREAD

**Issue by CCCAUCHY** [juicity/juicity#41]
## What feature you would like us to integrate into the juicity project
能否提供TLS1.3里支持的chacha20-poly1305套件和socks5鉴权
## Why is this needed
低性能设备上部署

**Comment by mzz2017** [comment]
@CCCAUCHY socks5 鉴权，listen 写 username:password@:1080

**Comment by mzz2017** [comment]
根据 https://go.dev/blog/tls-cipher-suites ，golang 会自动根据硬件支持来选择 cipher 套件。
