### ISSUE TITLE
是否考虑后期做中转服务？

### ISSUE THREAD

**Issue by miniso520** [juicity/juicity#50]
目前看到的是通过客户端与服务端，建立一个隧道进行数据传输。那我理解我可以把这个隧道当作一个中转隧道来中转我中转我的落地服务器？！希望能加入这样的功能。这样的话，相当于拓展了tuic服务。

**Comment by mzz2017** [comment]
@miniso520 用 juicity-client 开个 sock5/http 混合监听就可以

**Comment by miniso520** [comment]
> @miniso520 用 juicity-client 开个 sock5/http 混合监听就可以
你是指通过在通过机器的监听来进行转发是吧。那到可以。有空我来实验下。

**Comment by chika0801** [comment]
https://github.com/juicity/juicity/discussions/27

@miniso520 你是想问服务端能否增加socks出站吗？

**Comment by miniso520** [comment]
> #27
> 
> @miniso520 你是想问服务端能否增加socks出站吗？

是的。想组建类似gost这样的一个隧道。进行中转服务

**Comment by mzz2017** [comment]
https://github.com/juicity/juicity/pull/86 解决了你的问题吗，可以帮忙测试一下 https://github.com/juicity/juicity/actions/runs/5847037859
