### ISSUE TITLE
请问是否与tuic协议兼容？

### ISSUE THREAD

**Issue by moranno** [juicity/juicity#55]
请问是否与tuic协议兼容？

比如我使用兼容tuic协议的shadowrocket能否链接juicity的服务端？

另外请问下juicity的bbr是如何实现的？好像quic-go库还不支持bbr。

**Comment by mzz2017** [comment]
> 请问是否与tuic协议兼容？

不兼容

> 另外请问下juicity的bbr是如何实现的？好像quic-go库还不支持bbr。

基于 quic-go 的 fork 的版本，和 meta 的 bbr 是一个版本。

**Comment by moranno** [comment]
> > 另外请问下juicity的bbr是如何实现的？好像quic-go库还不支持bbr。
> 
> 基于 quic-go 的 fork 的版本，和 meta 的 bbr 是一个版本。

有没有测试下fork的quic-go bbr实现和rust的bbr实现是否有速度差异？

**Comment by mzz2017** [comment]
> 有没有测试下fork的quic-go bbr实现和rust的bbr实现是否有速度差异？
> 
> 

https://github.com/juicity/juicity/issues/30#issuecomment-1657342818
