### ISSUE TITLE
希望增加一个生成 uuid 的命令，如 juicity uuid

### ISSUE THREAD

**Issue by chika0801** [juicity/juicity#63]
希望增加一个生成 uuid 的命令，如 juicity uuid，随机生成一个 uuid

## What feature you would like us to integrate into the juicity project

Available Commands:
  help        Help about any command
  run         To run juicity-server in the foreground.

**Comment by wanlce** [comment]
有个命令叫 uuidgen ， 如图所示
![image](https://github.com/juicity/juicity/assets/55907021/82d9dd69-3cf1-43ad-afd5-f6dfa7e085db)

**Comment by chika0801** [comment]
谢谢您的帮助

**Comment by QIN2DIM** [comment]
@chika0801 debian?

```bash
python3 -c "from uuid import uuid4;print(uuid4())"
```

**Comment by mzz2017** [comment]
@chika0801 https://www.v2fly.org/awesome/tools.html

**Comment by yqlbu** [comment]
@mzz2017 Shall we add this ref link in our docs?

**Comment by mzz2017** [comment]
@yqlbu Good suggestion

**Comment by yqlbu** [comment]
@mzz2017 I will work on it later.
