### ISSUE TITLE
[Feature Request]能否考虑增加端口跳跃的支持

### ISSUE THREAD

**Issue by egg1234** [juicity/juicity#65]
## What feature you would like us to integrate into the juicity project
能否考虑增加端口跳跃的支持

## Why is this needed
规避udp包被qos的问题

谢谢！

**Comment by mzz2017** [comment]
QoS 的问题不应该通过端口跳跃来解决。几年前（Victoria 还在时），v2ray 引入了[动态端口](https://www.v2fly.org/developer/protocols/vmess.html#%E5%8A%A8%E6%80%81%E7%AB%AF%E5%8F%A3%E6%8C%87%E4%BB%A4)的功能，但随后，动态端口加剧了被封的概率，至今已经废弃了。

我认为不应该再走过去的路，即使它目前可以一定程度上规避 QoS 的问题，但它不是一个长期且好的解法。我们应该使用更好的策略，例如通过 [udp2raw](https://github.com/wangyu-/udp2raw) 伪装成 tcp 流。

**Comment by mzz2017** [comment]
暂时先观望吧！

**Comment by mzz2017** [comment]
@egg1234 没关系，喜欢哪个用哪个

**Comment by yqlbu** [comment]
@egg1234 沒關係，你可以繼續用sing-box。

**Comment by yqlbu** [comment]
Close as not planned.
