### ISSUE TITLE
[Feature Request]能否考虑增加端口转发的功能

### ISSUE THREAD

**Issue by egg1234** [juicity/juicity#66]
## What feature you would like us to integrate into the juicity project
能否考虑增加端口转发的功能

## Why is this needed
方便转发具体端口号的服务，避免代理方式导致服务器端整个网段可被访问

**Comment by mzz2017** [comment]
具体点呢？你理解上的端口转发具体做什么事情？

**Comment by mzz2017** [comment]
@egg1234 可以的

**Comment by miniso520** [comment]
> @egg1234 可以的



> @egg1234 可以的

有具体的demo吗。我其实是想通过客户端与服务端组建隧道，通过组建公网隧道进行转发。

**Comment by mzz2017** [comment]
暂时没有实现，需要一点时间。

**Comment by mzz2017** [comment]
https://github.com/juicity/juicity/pull/86 解决了你的问题吗，可以帮忙测试一下 https://github.com/juicity/juicity/actions/runs/5847037859

**Comment by Terutoki** [comment]
> #86 解决了你的问题吗，可以帮忙测试一下 https://github.com/juicity/juicity/actions/runs/5847037859

<img width="295" alt="image" src="https://github.com/juicity/juicity/assets/31648892/5533a40e-ee02-468d-89e2-bf57fe445c3a">
非常感谢大佬实现这个功能，我这里测试是OK的，可以成功转发Xray的trojan和gRPC，中转机是V6的。我现在已经用Juicity的中转隧道代替Hysteria的中转隧道了。

**Comment by moranno** [comment]
> #86 解决了你的问题吗，可以帮忙测试一下 https://github.com/juicity/juicity/actions/runs/5847037859

感谢！非常实用的功能，目前就2个请求：
1.是上面说的udp和tcp转发可以分开配置
2.是能否增加负载均衡和心跳检测功能?
比如使用round-robin基于权重对目标地址进行轮询，如果某个服务器心跳检测失败则踢出负载均衡组，心跳检测通过则重新加回。

**Comment by mzz2017** [comment]
> 比如使用round-robin基于权重对目标地址进行轮询，如果某个服务器心跳检测失败则踢出负载均衡组，心跳检测通过则重新加回。

这个功能建议套娃实现

**Comment by yqlbu** [comment]
@mzz2017 這個功能建議用外置的反向代理實現例如 nginx，caddy，kong，traefik，haproxy等。

**Comment by mzz2017** [comment]
@egg1234 @moranno 已增加分开 tcp/udp 的功能。

**Comment by moranno** [comment]
> > 比如使用round-robin基于权重对目标地址进行轮询，如果某个服务器心跳检测失败则踢出负载均衡组，心跳检测通过则重新加回。
> 
> 这个功能建议套娃实现

这样岂不是又多了一层转发，增加了延迟、内存、性能消耗？

**Comment by mzz2017** [comment]
> 这样岂不是又多了一层转发，增加了延迟、内存、性能消耗？

这的确是个振奋人心的功能，我们可以保留这个 issue，如果后面有时间的话可以考虑支持。

另一个解决方法是去已有的项目中提交 issue 来支持 Juicity，目前已经有许多项目具有类似的功能，我最喜欢的是 [glider](https://github.com/nadoo/glider)，但它似乎就像是停止维护了，如果你对这个项目感兴趣，我可以为它添加一个 Juicity 分支。

**Comment by moranno** [comment]
> @egg1234 @moranno 已增加分开 tcp/udp 的功能。

刚刚测了下最新的action版本（之前没测过）在转发ss大流量下载或上传测试的过程种容易出现断流，表现为网络完全不通；重启客户端或服务端均可以恢复。

拓扑：ss ------> juic client forwarder-------> juic server ------> ss server

日志无明显报错，下面日志并不是断流时候的日志，只是部分截取：

```
服务端日志：
2023-08-15 00:14:41 WRN server.go:166 > error="relay tcp error: read tcp 127.0.0.1:57440->127.0.0.1:55224: read: connection reset by peer"
2023-08-15 00:14:41 DBG server.go:194 > juicity received a tcp request source=53.64.21.2:54682 target=127.0.0.1:55224
2023-08-15 00:14:41 DBG server.go:194 > juicity received a tcp request source=53.64.21.2:54682 target=127.0.0.1:55224

客户端日志：
2023-08-14 16:26:35 INF forwarder.go:126 > Forward 120.34.222.12:63418 <-tcp-> 127.0.0.1:55224
2023-08-14 16:26:42 WRN forwarder.go:134 > error="readfrom tcp 120.233.42.93:15398->120.34.222.12:63417: write tcp 120.233.42.93:15398->120.34.222.12:63417: write: broken pipe"
2023-08-14 16:26:43 INF forwarder.go:126 > Forward 120.34.222.12:63425 <-tcp-> 127.0.0.1:55224
```

**Comment by mzz2017** [comment]
@moranno 应该是被 qos 了，套个 udp2raw 的 faketcp 试试
