### ISSUE TITLE
[Request] Add socks5 outbound on the server side for routing

### ISSUE THREAD

**Issue by showgood163** [juicity/juicity#72]
## What would you like us to improve

Add socks5 outbound on the server side for routing

## Why is this needed

Socks5 outbound on the server side is required to use *ray for routing.

**Comment by mzz2017** [comment]
Good idea. I'll consider it.
By the way, you can also use `fwmark` and use `iptables` to send the traffic into a `dokodemodoor` inbound.

**Comment by showgood163** [comment]
> Good idea. I'll consider it. By the way, you can also use `fwmark` and use `iptables` to send the traffic into a `dokodemodoor` inbound. Juicity-server supports `fwmark`.

OK, I'll take a look at `fwmark`.

**Comment by showgood163** [comment]
> @showgood163 #92 Please test it. Thank you.

I only tested socks5 outbound and saw no problem.
