### ISSUE TITLE
[Support Request] <title>关闭ssh后自动停止

### ISSUE THREAD

**Issue by wanxiaochao** [juicity/juicity#82]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

ubuntu系统  启动命令 nohup ./juicity-client run -c example-client.json >> output.out 2>&1 &  关闭ssh后客户端自动停止了

### Environment

- **Juicity version (use `juicity --version`)**:
- **OS (e.g `cat /etc/os-release`)**:
- **Kernel (e.g. `uname -a`)**:
- **Others**:

**Comment by MarksonHon** [comment]
这是预期行为，服务器上的sshd会话进程退出后，对应的子进程也会被关闭，建议使用systemctl来管理服务，使用[官方安装器](https://github.com/juicity/juicity-installer)进行安装。

**Comment by QIN2DIM** [comment]
### Systemctl
（推荐）你可以使用项目相关的部署脚本，自动挂起 service，通过系统服务来维护代理。这种情况下可以方便进行开机自启，意外中断重启，资源容器限制等有关进程生命周期的调度。


### Tmux
或者出于测试用途，你可以使用 `tmux` 分割出一个 session 运行进程，这样关闭 ssh 会话后依然可以继续运行。

1. Install `tmux` (on ubuntu)

```bash
apt install -y tmux
```

2. Create session
```bash
tmux new -s juicity
```

3. Run juicity-client
```bash
path/to/juicity-client run -c path/to/example-client.json
```

**Comment by wanxiaochao** [comment]
谢谢！
