### ISSUE TITLE
[Bug Report] cannot run on router with old kernel

### ISSUE THREAD

**Issue by showgood163** [juicity/juicity#89]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

Juicity-client can not listen on specific port properly

```
juicity run -c conf.json
panic: unaligned 64-bit atomic operation

goroutine 5 [running]:
runtime/internal/atomic.panicUnaligned()
        runtime/internal/atomic/unaligned.go:8 +0x24
runtime/internal/atomic.Load64(0xc87974)
        runtime/internal/atomic/atomic_arm.s:280 +0x14
github.com/daeuniverse/softwind/protocol/juicity.(*clientRing).Dial.func1(0xc87970)
        github.com/daeuniverse/softwind@v0.0.0-20230805041143-2db4e28c8922/protocol/juicity/client_ring.go:46 +0x6c
github.com/daeuniverse/softwind/protocol/juicity.(*clientRing)._tryNext(0xc00040, 0xc90dbc, 0xc90dc8)
        github.com/daeuniverse/softwind@v0.0.0-20230805041143-2db4e28c8922/protocol/juicity/client_ring.go:98 +0x350
github.com/daeuniverse/softwind/protocol/juicity.(*clientRing).Dial(0xc00040, {0x58f2e0, 0xca0014}, 0xc8a1b0, {0x58d554, 0xc0c010}, 0xca2210)
        github.com/daeuniverse/softwind@v0.0.0-20230805041143-2db4e28c8922/protocol/juicity/client_ring.go:45 +0xf4
github.com/daeuniverse/softwind/protocol/juicity.(*Dialer).Dial(0xc56018, {0x4f0542, 0x3}, {0xcca0e0, 0x1c})
        github.com/daeuniverse/softwind@v0.0.0-20230805041143-2db4e28c8922/protocol/juicity/dialer.go:128 +0x330
github.com/juicity/juicity/server.(*forwarder).Dial(0xc0e020, {0x4f0542, 0x3}, {0xcca0e0, 0x1c})
        github.com/juicity/juicity/server/mixed_server.go:41 +0x48
github.com/nadoo/glider/proxy/socks5.(*Socks5).Serve(0xc5a030, {0x5914f0, 0xc87930})
        github.com/nadoo/glider@v0.16.3/proxy/socks5/server.go:84 +0x27c
github.com/juicity/juicity/server.(*Mixed).Serve(0xc0c020, {0x591550, 0xc0e068})
        github.com/juicity/juicity/server/mixed_server.go:139 +0xac
created by github.com/juicity/juicity/server.(*Mixed).ListenAndServe
        github.com/juicity/juicity/server/mixed_server.go:130 +0x2a4
```

### Expected Behavior

Juicity-client can work properly

### Steps to Reproduce

1. get a router w/ broadcom cpu
2. install freshtomato 2023.3 firmware
3. run juicity-client

### Environment

- **Juicity version (use `juicity --version`)**:
v0.1.2 armv5

- **OS (e.g `cat /etc/os-release`)**:
freshtomato 2023.3

- **Kernel (e.g. `uname -a`)**:
```
Linux unknown 2.6.36.4brcmarm #18 SMP PREEMPT Wed Jun 21 22:16:03 CEST 2023 armv7l Tomato
```

### Anything else?
Here is the config:
{
    "listen": ":1080",
    "server": "xxx",
    "uuid": "xxx",
    "password": "xxx",
    "sni": "xxx",
    "allow_insecure": false,
    "congestion_control": "bbr",
    "log_level": "warn"
}

**Comment by mzz2017** [comment]
What arch do you download? You should try the armv7 one.

**Comment by showgood163** [comment]
> What arch do you download? You should try the armv7 one.

I forgot to say that.

I use armv5 version. I cannot run armv7 version because of 
```
Illegal instruction
```

**Comment by mzz2017** [comment]
How about other golang softwares? Can everything goes right?

I'm not sure this is a general problem or just some bug of juicity.

If iy is a general problem, maybe some tricks need to utilize. As I known, some float units are trimmed in some chips. So please double check it. Thank you!

**Comment by showgood163** [comment]
Emmm, I'm not sure about the problem you're talking about.

Should I focus on the `Illegal instruction` problem? Or the problem I reported?

**Comment by mzz2017** [comment]
Maybe you can also search

```
unaligned 64-bit atomic operation
```

But I searched it and found no good news in the first search result.

**Comment by mzz2017** [comment]
https://github.com/minio/minio/pull/14568

This should be a good solution. However, I have no such 32-bit device. I'm thinking how to reproduce it for a better fix.

**Comment by showgood163** [comment]
> Maybe you can also search
> 
> ```
> unaligned 64-bit atomic operation
> ```
> 
> But I searched it and found no good news in the first search result.

Try this keyword in googld:

```
go unaligned 64-bit atomic operation site:github.com
```

**Comment by showgood163** [comment]
> [minio/minio#14568](https://github.com/minio/minio/pull/14568)
> 
> This should be a good solution. However, I have no such 32-bit device. I'm thinking how to reproduce it for a better fix.

One possible solution is QEMU (may take a lot of time to setup).

https://www.qemu.org/docs/master/system/target-arm.html

https://www.qemu.org/docs/master/system/arm/emulation.html

**Comment by mzz2017** [comment]
#91
Could you please test it? I have tested it using `qemu-arm-static`, and it works fine.

**Comment by showgood163** [comment]
> #91 Could you please test it? I have tested it using `qemu-arm-static`, and it works fine.

No. I see the same `Illegal instruction`.

**Comment by mzz2017** [comment]
@showgood163 Where you get the binary? What is the output?

**Comment by mzz2017** [comment]
@showgood163 https://github.com/juicity/juicity/actions/runs/5857054441/

**Comment by showgood163** [comment]
> @showgood163 Where you get the binary? What is the output?

I added these lines in `Makefile` and compiled the client by myself:
```
export GOOS=linux
export GOARCH=arm
export GOARM=7
export CGO_ENABLED=0
```

However, I also tested `export GOARM=5` and it worked.

**Comment by mzz2017** [comment]
@showgood163 So, you mean the problem has been fixed?

**Comment by showgood163** [comment]
> @showgood163 https://github.com/juicity/juicity/actions/runs/5857054441/

I see no usable files. Can you check again?

**Comment by mzz2017** [comment]
@showgood163 https://github.com/juicity/juicity/actions/runs/5857054487   Sorry.

**Comment by showgood163** [comment]
> @showgood163 So, you mean the problem has been fixed?

Kind of. At least the compatibility of juicity is the same xray/v2ray now.

**Comment by mzz2017** [comment]
Good to hear that.

**Comment by showgood163** [comment]
> @showgood163 https://github.com/juicity/juicity/actions/runs/5857054487 Sorry.

The armv7 binary still shows `Illegal instruction` so no luck.

**Comment by mzz2017** [comment]
@showgood163 It is mostly a chip problem.

**Comment by showgood163** [comment]
> @showgood163 It is mostly a chip problem.

Ok.
