### ISSUE TITLE
[Bug Report] juicity startup failure

### ISSUE THREAD

**Issue by ItTonySuperMan** [juicity/juicity#94]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Current Behavior

juicity fails to start. Attempted to launch the juicity server using the command
```
 ./juicity-server run -c config.json.
```
Error Report:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x759954]

goroutine 1 [running]:
github.com/rs/zerolog.(*Logger).should(0xc0000b1680?, 0x0?)
        github.com/rs/zerolog@v1.30.0/log.go:491 +0x14
github.com/rs/zerolog.(*Logger).newEvent(0x0, 0x4, 0xa74c38)
        github.com/rs/zerolog@v1.30.0/log.go:466 +0x45
github.com/rs/zerolog.(*Logger).Fatal(0xc000055cf8?)
        github.com/rs/zerolog@v1.30.0/log.go:388 +0x25
main.glob..func3(0xe4dae0?, {0xa27626?, 0x2?, 0x2?})
        github.com/juicity/juicity/cmd/server/run.go:42 +0x11a
github.com/spf13/cobra.(*Command).execute(0xe4dae0, {0xc00005f2e0, 0x2, 0x2})
        github.com/spf13/cobra@v1.7.0/command.go:944 +0x847
github.com/spf13/cobra.(*Command).ExecuteC(0xe4d240)
        github.com/spf13/cobra@v1.7.0/command.go:1068 +0x3bd
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.7.0/command.go:992
main.Execute(...)
        github.com/juicity/juicity/cmd/server/cmd.go:22
main.main()
        github.com/juicity/juicity/cmd/server/server.go:6 +0x25
```

### Expected Behavior

Expecting successful launch of juicity server with no error reports.

### Steps to Reproduce

1. Download juicity-server version unstable-20230815.r94.dd017c2
2. Use command chmod 777 juicity-server to grant file permissions
3. Execute command ./juicity-server run -c config.json
4. Encounter error report

### Environment

- **Juicity version (use `juicity --version`)**:  version unstable-20230815.r94.dd017c2
- **OS (e.g `cat /etc/os-release`)**:  Debian 11
- **Kernel (e.g. `uname -a`)**:  5.10.0-8-amd64  Debian 5.10.46-4 (2021-08-03)
- **Others**:

**Comment by mzz2017** [comment]
@ItTonySuperMan 应该是你的 log level 设错了

**Comment by ItTonySuperMan** [comment]
> @ItTonySuperMan 应该是你的 log level 设错了

Indeed, the log level was mistakenly written as 'dbg' instead of the complete 'debug'. 
Thank you for your response, much appreciated. Thank you.
