### ISSUE TITLE
[Support Request] juicity occasional usage exception

### ISSUE THREAD

**Issue by ItTonySuperMan** [juicity/juicity#95]
### Checks

- [X] I have searched the existing issues
- [X] I have read the documentation
- [X] Is it your first time sumbitting an issue

### Support Request

When using juicity, it can be used occasionally and occasionally loses connection. But when the connection is lost, do not use the broadband provided by the isp to change the mobile data connection, juicity is normal

### **server configuration**
```
QUIC_GO_ENABLE_GSO=true
{
  "listen": ":23182",
  "users": {
    "00000000-0000-0000-0000-000000000000": "my_password"
  },
  "certificate": "/path/to/fullchain.cer",
  "private_key": "/path/to/private.key",
  "congestion_control": "bbr",
  "log_level": "debug"
}
```

### **client configuration**
```
QUIC_GO_ENABLE_GSO=true
    "listen": ":3630",
    "server": "abc.com:23182",
    "uuid": "00000000-0000-0000-0000-000000000000",
    "password": "my_password",
    "sni": "abc.com",
    "allow_insecure": false,
    "congestion_control": "bbr",
    "log_level": "debug"
```

### **server error report**
```
Aug 19 12:52:12 localhost.localdomain juicity-server[578]: <nil> WRN server.go:150 > handleAuth error="context deadline exceeded"
Aug 19 12:52:12 localhost.localdomain juicity-server[578]: <nil> WRN server.go:134 > error="context canceled"
```

### **client error report**
```
relay error: timeout: no recent network activity
relay error: Application error 0xfffffff1 (remote)
error in dial: OpenStream: Application error 0xfffffff1 (remote)
wsarecv: An existing connection was forcibly closed by the remote host.
```

### Expected Behavior

normal use of juicity

### Environment

- **Juicity version (use `juicity --version`)**: version unstable-20230815.r94.dd017c2
- **OS (e.g `cat /etc/os-release`)**: Debian 11
- **Kernel (e.g. `uname -a`)**: 5.10.0-8-amd64 Debian 5.10.46-4 (2021-08-03)
- **Others**:

**Comment by mzz2017** [comment]
@ItTonySuperMan 这是udp被运营商qos了

**Comment by yqlbu** [comment]
@ItTonySuperMan please try using udp 443 (h3)

**Comment by ItTonySuperMan** [comment]
> @ItTonySuperMan 这是udp被运营商qos了

does it mean that port transitions are needed, similar to hysterical protocols, to avoid operator QoS?

**Comment by ItTonySuperMan** [comment]
> @ItTonySuperMan please try using udp 443 (h3)

this is a good suggestion, udp 443 is more in line with the rules of quic flow, but I am afraid that the long-term udp single-port connection will still be subject to qos by the operator

**Comment by yqlbu** [comment]
> > @ItTonySuperMan please try using udp 443 (h3)
> 
> this is a good suggestion, udp 443 is more in line with the rules of quic flow, but I am afraid that the long-term udp single-port connection will still be subject to qos by the operator

I've been using `udp 443` for weeks. It's much more stable than port other than 443. Please give it a try.

**Comment by ItTonySuperMan** [comment]
> > > @ItTonySuperMan please try using udp 443 (h3)
> > 
> > 
> > this is a good suggestion, udp 443 is more in line with the rules of quic flow, but I am afraid that the long-term udp single-port connection will still be subject to qos by the operator
> 
> I've been using `udp 443` for weeks. It's much more stable than ports other than 443. Please give it a try.

okay, I'll give it a try and see if it can be improved. Thank you for your suggestion

**Comment by ItTonySuperMan** [comment]
> > > @ItTonySuperMan please try using udp 443 (h3)
> > 
> > 
> > this is a good suggestion, udp 443 is more in line with the rules of quic flow, but I am afraid that the long-term udp single-port connection will still be subject to qos by the operator
> 
> I've been using `udp 443` for weeks. It's much more stable than ports other than 443. Please give it a try.

Replace 443, the problem will still appear after using it for a while

**Comment by yqlbu** [comment]
Any updates?
