### ISSUE TITLE
[Feature Request]能否增加"alpn"的自定义

### ISSUE THREAD

**Issue by egg1234** [juicity/juicity#99]
### Feature Request

能否增加"alpn"的自定义？像下面这样：
"alpn": ["h3", "spdy/3.1"],

谢谢！

### Potential Benefits

增加quic包的多样性

**Comment by mzz2017** [comment]
有什么用？

**Comment by yqlbu** [comment]
tuic 的參數在 juicity 不一定完全適用。

**Comment by mzz2017** [comment]
目前是写死的 h3

**Comment by mzz2017** [comment]
目前来说，增加其他的 alpn 不会有显著区别，所以暂时不会有开放 alpn 自定义的打算
